# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               "French PowerShell User Group"
tagline:             "Groupe d'utilisateurs PowerShell francophone"
description:         "French PowerShell User Group"
url:                 http://frpsug.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              FrPSUG
  url:               https://twitter.com/frpsug
  email:             frpsug@gmail.com

# Custom vars
version:             1.0.0

# Social
meetup:
  name:              'Meetup'
  url:               'http://meetup.com/frenchpsug'
twitter:             
  name:              'FrPSUG'
  url:               'http://twitter.com/frpsug'

# Github
github:              
  organization:      
    name:            'Suivez nous sur @FrPSUG'
    url:             'https://github.com/orgs/FrPSUG/dashboard'
  repo:
    presentations:      
      name:            'Presentations'
      url:             'https://github.com/FrPSUG/Presentations'